/** @readonly */
export const POOL_SIZE = 100;
export const QUIZ_LENGTH = 10;
export const ANCHOR_IDS = ["q002", "q003", "q007", "q010"];
export const SESSION_MAX_SCORE = 22;

/** Random slot weight budget: 6 questions must sum to this (anchors sum to 11) */
export const RANDOM_WEIGHT_BUDGET = 11;

/**
 * @type {ReadonlyArray<{ id: string, weight: 1|2|3, anchor?: boolean, category: string, tags?: string[] }>}
 */
export const QUESTION_POOL = [
  { id: "q001", weight: 1, category: "culture", tags: ["ppt", "montana"] },
  { id: "q002", weight: 3, anchor: true, category: "comp", tags: ["pip", "downgrade"] },
  { id: "q003", weight: 3, anchor: true, category: "leadership", tags: ["promesa", "ascenso"] },
  { id: "q004", weight: 2, category: "politics", tags: ["evaluacion", "doble"] },
  { id: "q005", weight: 1, category: "leadership", tags: ["openbar", "offsite"] },
  { id: "q006", weight: 2, category: "workload", tags: ["evento", "recorte"] },
  { id: "q007", weight: 2, anchor: true, category: "comp", tags: ["grading", "techo"] },
  { id: "q008", weight: 1, category: "leadership", tags: ["1on1", "apoyo"] },
  { id: "q009", weight: 2, category: "hr", tags: ["grading", "niveles"] },
  { id: "q010", weight: 3, anchor: true, category: "hr", tags: ["subnivel", "estancamiento"] },
  { id: "q011", weight: 1, category: "politics", tags: ["whatsapp", "rumor"] },
  { id: "q012", weight: 2, category: "remote", tags: ["rto", "mandato"] },
  { id: "q013", weight: 3, category: "tech", tags: ["oncall", "weekend"] },
  { id: "q014", weight: 1, category: "workload", tags: ["scope", "creep"] },
  { id: "q015", weight: 3, category: "comp", tags: ["bonus", "recorte"] },
  { id: "q016", weight: 1, category: "culture", tags: ["values", "poster"] },
  { id: "q017", weight: 2, category: "jp", tags: ["nomikai", "afterwork"] },
  { id: "q018", weight: 1, category: "latam", tags: ["nochebuena", "regalo"] },
  { id: "q019", weight: 3, category: "politics", tags: ["credit", "robo"] },
  { id: "q020", weight: 2, category: "leadership", tags: ["allhands", "qna"] },
  { id: "q021", weight: 1, category: "hr", tags: ["nps", "encuesta"] },
  { id: "q022", weight: 1, category: "remote", tags: ["zoom", "camara"] },
  { id: "q023", weight: 3, category: "workload", tags: ["afterhours", "mensaje"] },
  { id: "q024", weight: 2, category: "tech", tags: ["hotfix", "viernes"] },
  { id: "q025", weight: 1, category: "comp", tags: ["equity", "refresh"] },
  { id: "q026", weight: 1, category: "culture", tags: ["freefood", "pizza"] },
  { id: "q027", weight: 3, category: "politics", tags: ["proxy", "war"] },
  { id: "q028", weight: 1, category: "leadership", tags: ["reorg", "silencio"] },
  { id: "q029", weight: 2, category: "hr", tags: ["pip", "plan"] },
  { id: "q030", weight: 1, category: "workload", tags: ["jira", "ticket"] },
  { id: "q031", weight: 2, category: "tech", tags: ["ai", "copilot"] },
  { id: "q032", weight: 3, category: "remote", tags: ["timezone", "overlap"] },
  { id: "q033", weight: 1, category: "comp", tags: ["clawback", "bonus"] },
  { id: "q034", weight: 1, category: "culture", tags: ["swag", "hoodie"] },
  { id: "q035", weight: 2, category: "jp", tags: ["senpai", "junior"] },
  { id: "q036", weight: 2, category: "latam", tags: ["whatsapp", "urgente"] },
  { id: "q037", weight: 2, category: "politics", tags: ["bcc", "hr"] },
  { id: "q038", weight: 3, category: "leadership", tags: ["micromanagement", "control"] },
  { id: "q039", weight: 1, category: "hr", tags: ["compliance", "training"] },
  { id: "q040", weight: 2, category: "workload", tags: ["domingo", "mail"] },
  { id: "q041", weight: 2, category: "tech", tags: ["techdebt", "sprint"] },
  { id: "q042", weight: 1, category: "remote", tags: ["hibrido", "asistencia"] },
  { id: "q043", weight: 3, category: "comp", tags: ["headcount", "freeze"] },
  { id: "q044", weight: 2, category: "culture", tags: ["teambuilding", "confianza"] },
  { id: "q045", weight: 2, category: "politics", tags: ["calibracion", "foro"] },
  { id: "q046", weight: 1, category: "leadership", tags: ["deck", "roadmap"] },
  { id: "q047", weight: 2, category: "hr", tags: ["360", "feedback"] },
  { id: "q048", weight: 3, category: "workload", tags: ["utilizacion", "target"] },
  { id: "q049", weight: 1, category: "tech", tags: ["legacy", "code"] },
  { id: "q050", weight: 2, category: "remote", tags: ["corehours", "mandatory"] },
  { id: "q051", weight: 2, category: "comp", tags: ["signing", "bonus"] },
  { id: "q052", weight: 3, category: "culture", tags: ["happyhour", "obligatorio"] },
  { id: "q053", weight: 2, category: "jp", tags: ["gaijin", "local"] },
  { id: "q054", weight: 1, category: "latam", tags: ["duolingo", "ingles"] },
  { id: "q055", weight: 2, category: "politics", tags: ["glassdoor", "review"] },
  { id: "q056", weight: 3, category: "leadership", tags: ["manager", "skip"] },
  { id: "q057", weight: 2, category: "hr", tags: ["pto", "blackout"] },
  { id: "q058", weight: 2, category: "workload", tags: ["bench", "proyecto"] },
  { id: "q059", weight: 3, category: "tech", tags: ["monitoring", "productividad"] },
  { id: "q060", weight: 1, category: "remote", tags: ["hotdesk", "reserva"] },
  { id: "q061", weight: 2, category: "comp", tags: ["billable", "hours"] },
  { id: "q062", weight: 1, category: "culture", tags: ["mission", "vision"] },
  { id: "q063", weight: 3, category: "politics", tags: ["replyall", "drama"] },
  { id: "q064", weight: 2, category: "leadership", tags: ["matrix", "dotted"] },
  { id: "q065", weight: 1, category: "hr", tags: ["sick", "proof"] },
  { id: "q066", weight: 2, category: "workload", tags: ["feriado", "deploy"] },
  { id: "q067", weight: 2, category: "tech", tags: ["chatgpt", "policy"] },
  { id: "q068", weight: 3, category: "remote", tags: ["badge", "scan"] },
  { id: "q069", weight: 1, category: "comp", tags: ["referral", "bonus"] },
  { id: "q070", weight: 2, category: "culture", tags: ["diversity", "slide"] },
  { id: "q071", weight: 3, category: "jp", tags: ["kaizen", "mejora"] },
  { id: "q072", weight: 2, category: "latam", tags: ["tercerizacion", "vendor"] },
  { id: "q073", weight: 2, category: "politics", tags: ["junior", "blame"] },
  { id: "q074", weight: 1, category: "leadership", tags: ["agile", "ceremonia"] },
  { id: "q075", weight: 3, category: "hr", tags: ["parental", "leave"] },
  { id: "q076", weight: 2, category: "workload", tags: ["cliente", "prioridad"] },
  { id: "q077", weight: 2, category: "tech", tags: ["vendor", "lockin"] },
  { id: "q078", weight: 1, category: "remote", tags: ["homeoffice", "kit"] },
  { id: "q079", weight: 3, category: "comp", tags: ["lateral", "move"] },
  { id: "q080", weight: 2, category: "culture", tags: ["trustfall", "ejercicio"] },
  { id: "q081", weight: 2, category: "politics", tags: ["cc", "boss"] },
  { id: "q082", weight: 3, category: "leadership", tags: ["burnout", "wellness"] },
  { id: "q083", weight: 2, category: "hr", tags: ["maternity", "return"] },
  { id: "q084", weight: 1, category: "workload", tags: ["standup", "daily"] },
  { id: "q085", weight: 2, category: "tech", tags: ["cloud", "bill"] },
  { id: "q086", weight: 2, category: "remote", tags: ["slack", "urgente"] },
  { id: "q087", weight: 3, category: "comp", tags: ["demotion", "title"] },
  { id: "q088", weight: 1, category: "culture", tags: ["branding", "valores"] },
  { id: "q089", weight: 2, category: "jp", tags: ["afterwork", "obligatorio"] },
  { id: "q090", weight: 3, category: "latam", tags: ["ghosting", "postulacion"] },
  { id: "q091", weight: 2, category: "politics", tags: ["staff", "title"] },
  { id: "q092", weight: 1, category: "leadership", tags: ["claridad", "rol"] },
  { id: "q093", weight: 2, category: "hr", tags: ["vacaciones", "aprobacion"] },
  { id: "q094", weight: 3, category: "workload", tags: ["oncall", "pager"] },
  { id: "q095", weight: 2, category: "tech", tags: ["documentacion", "deuda"] },
  { id: "q096", weight: 2, category: "remote", tags: ["focus", "time"] },
  { id: "q097", weight: 1, category: "comp", tags: ["stock", "refresh"] },
  { id: "q098", weight: 3, category: "culture", tags: ["powerpoint", "offsite"] },
  { id: "q099", weight: 2, category: "politics", tags: ["intern", "coffee"] },
  { id: "q100", weight: 2, category: "leadership", tags: ["gafas", "renuncia"] },
];
