/** @readonly EITPL question pool — English (100 items) */
export const POOL_TEXTS_EN = {
  q001: "Does your company use mountain or mountaineering metaphors in HR presentations?",
  q002: "Did your company give a fancy name like 'band restructuring' to what, in plain English, was just a pay cut?",
  q003: "Were you promised a promotion that has been more than 6 months without materializing?",
  q004: "Are mistakes held against you in reviews only when they're yours, but not when your lead makes them?",
  q005: "Is the company in cost-cutting mode but managers still go to offsites with open bar?",
  q006: "Were you asked to organize a company event after layoffs were announced?",
  q007: "Did they explain the new grading system with a chart so complicated that not even HR could tell you which band you were actually in?",
  q008: "The last time you asked about your promotion, were you told 'we've got your back' with no concrete date?",
  q009: "Does the evaluation system now have more levels, more acronyms, and more meetings, but somehow moving up a single step is harder than before?",
  q010: "Have you been 'about to level up' for months now, to the point it's become an inside joke on your team?",
  q011: "Were you called to a 1:1 to be told you left early one day, while word is going around that 'everyone is disengaged' even though you don't lead the team or even the floor Slack channel?",
  q012: "Do you receive WhatsApp messages from your manager after 10pm followed by 'not urgent, reply when you can'?",
  q013: "Did your company announce mandatory return to office just when the most people were quitting?",
  q014: "Did the company hand out pizza to celebrate their best quarter ever while your raise request is still 'under review'?",
  q015: "Did your manager use the phrase 'we're a family here' with a completely straight face in the last 6 months?",
  q016: "Did the calibration meeting last four hours and you ended up with a lower rating than what you'd agreed with your lead?",
  q017: "Is there someone on your team who delivers less but has a better evaluation because they have 'good rapport' with the manager?",
  q018: "Are you on call or doing pager duty without it being reflected in any part of your compensation?",
  q019: "Was there a reorg that left you with exactly the same job but a different title that sounds like a demotion?",
  q020: "Did the company send an email about mental wellness or stress management at 11pm on a Tuesday?",
  q021: "Did your bonus arrive incomplete, late, or with an explanation that basically said 'trust us'?",
  q022: "Has your salary been frozen for over a year while inflation chipped away at your purchasing power in installments?",
  q023: "Did you present an initiative that was rejected, and months later your lead presented it as their own to the director?",
  q024: "Were you called into an 'informal' chat that turned out to be a formal improvement plan, with the only prior warning being your manager giving you a weird look in the hallway?",
  q025: "Is your company's rating curve so forced that even when the whole team hits its goals, someone still ends up labeled 'needs improvement'?",
  q026: "Did the daily standup turn into a meeting where your manager asks about each of your tasks in front of everyone?",
  q027: "Are there Jira tickets that have been open for months because nobody knows who the real owner is?",
  q028: "Does the sprint retro always end with the same three action items that never get implemented before the next retro?",
  q029: "Did the project scope grow 40% after kickoff without anyone adjusting the deadline or headcount?",
  q030: "Did the company announce a 'new strategic chapter' or 'transformation journey' in the same communication where they announced layoffs?",
  q031: "Was team building on a Friday night at a place the manager chose, and attendance was recorded somewhere?",
  q032: "Do HR emails talk about 'psychological safety' but raising a real problem has real consequences?",
  q033: "Does the company have a wellness program with a meditation app, yoga classes, and weekly newsletter, but no salary adjustment?",
  q034: "Were your vacation days denied for 'business needs' in the same period your manager was able to take theirs?",
  q035: "Did you fill out an employee satisfaction survey and the results were used to justify a policy that was clearly already decided?",
  q036: "Does your annual review feedback include situations from a year ago that were never mentioned to you at the time?",
  q037: "Did two key people leave the team and you were told you'd cover their responsibilities 'temporarily' with no change in compensation?",
  q038: "Was the whole team's bonus canceled for a 'bad year,' but leadership's offsite the following quarter was somewhere with a pool?",
  q039: "Does your company have an open-door policy but people who actually use it end up labeled 'difficult to work with'?",
  q040: "Were you given a promotion to a title that sounds better but salary and actual responsibilities are exactly the same?",
  q041: "Does nemawashi at your company consist of being so exhausted by prior consultations that by the time the formal decision arrives you don't object to anything?",
  q042: "Is attendance at nomikai or team dinners technically voluntary but those who don't go show up in reviews as 'not very committed'?",
  q043: "Did your company implement OKRs but your year-end evaluation has no verifiable connection to those objectives?",
  q044: "Are all-hands questions answered with pre-prepared slides and uncomfortable questions redirected to 'another channel'?",
  q045: "Has the roadmap changed so many times in the last quarter that you can no longer explain to an outsider exactly what you're working on?",
  q046: "Is there someone on your team who joined after you, earns more, and nobody can quite explain why?",
  q047: "Did a role that was 'eliminated due to restructuring' get reposted three months later under a different name?",
  q048: "Did you inherit a former teammate's tasks months ago, and is the 'it's temporary, we're hiring a replacement' still not true?",
  q049: "Do new hires get paid in dollars while you've been paid in local currency for years with the same title?",
  q050: "Do you have a stash of accrued vacation days you could never use, and does the number mysteriously keep shrinking in the HR system?",
  q051: "Can't your manager explain with concrete criteria what you need to achieve to move to the next level?",
  q052: "Is the People team that designed the new grading system not subject to the same grading system they designed?",
  q053: "Did the company announce 'record investment in people' in the same quarter they froze hiring and canceled training?",
  q054: "Did you get an 'exceeds expectations' rating but the raise didn't cover even half of that year's inflation?",
  q055: "Was your annual review done by someone who's known you for less time than it takes a coffee to go cold?",
  q056: "At your company, does being visible in the office matter more for promotion than concrete deliverables?",
  q057: "Are org chart changes that directly affect you announced Friday at 5pm by email?",
  q058: "Were you asked to complete a detailed self-assessment knowing the decision on your evaluation was already made before you submitted it?",
  q059: "Does your company have an 'innovation' initiative with its own logo, a beautiful deck, and stickers, but a real budget of exactly zero?",
  q060: "Does your company say it's agile but no real process changed in the last two years and waterfall is still the de facto standard?",
  q061: "Is system technical debt mentioned as a priority in every retro but never appears on the approved roadmap?",
  q062: "Is your '9-to-5' workday actually '9-to-whenever-it's-done,' and does that difference never show up on your paycheck?",
  q063: "When you asked for a raise, were you told 'the market' determines your compensation is fair without showing you any market data?",
  q064: "Is the official policy flexible remote work but your manager messages you if you're not active in chat before 9am?",
  q065: "Do training opportunities exist on the company portal but there's always a reason you can't access them this quarter?",
  q066: "Did your peers give you positive feedback in the 360 review but your manager lowered the final score 'to make it more balanced'?",
  q067: "Did the last reorg result in your manager now reporting to someone who has no idea what your area does?",
  q068: "Does mandatory return to office apply to your team but your main stakeholders keep working fully remote?",
  q069: "Has the hiring process for a position on your team taken more than six months but you're expected to deliver full-team results now?",
  q070: "Was the position you wanted offered to an outside candidate, and did you find out via LinkedIn before your own company told you?",
  q071: "Does the email about 'company values' always seem to land the same week layoff rumors are going around?",
  q072: "Did you survive weeks of full-on crunch, and was the only compensation a 'thanks team' email with a fire emoji?",
  q073: "Are you the informal onboarding reference for new hires without that affecting your official workload or evaluation?",
  q074: "Was the technical training budget cut but leadership retreat budget increased?",
  q075: "Is the task management system so complex you spend more time administrating work in the tool than doing the work itself?",
  q076: "Were you assigned as a mentor to a colleague with no formal recognition, no reduction in your workload, and no weight in your evaluation?",
  q077: "Did you have an awkward HR chat that later got summarized in an email with a version of events you don't quite recognize?",
  q078: "Does your company have a no-rehire policy but after you left they informally called you for 'specific consultations' without pay?",
  q079: "Did you work flat out for months on a project that was canceled the week before launch with no formal retrospective or recognition?",
  q080: "Did your actual responsibilities change significantly in the last year without your job description or compensation being updated?",
  q081: "Does your company have a continuous feedback policy but in practice the only feedback you regularly receive is negative?",
  q082: "Did sprint planning become theater where the manager arrives with scope already decided and the ceremony exists to pretend the team participated?",
  q083: "Were you sold flexible hours but your mandatory recurring meetings cover slots from 8am to 7pm?",
  q084: "When someone leaves the company, does the official story never match what the whole team already knew from the side chat?",
  q085: "Does the company measure engagement with an annual survey whose results are never shared or produce verifiable changes?",
  q086: "Does your lead talk about ownership and autonomy at every all-hands but in practice vetoed every important decision you made on your own?",
  q087: "Was your project budget cut mid-execution without anyone adjusting scope or delivery date?",
  q088: "Did you find out about a change that directly affects you in a group meeting with no prior notice, alongside people who have nothing to do with it?",
  q089: "Did the company organize a hackathon or innovation day but none of the ideas generated were implemented or appear on any roadmap?",
  q090: "Does your manager talk about long-term career plans at the company when they've been in the role for less than a year?",
  q091: "Were you asked to sign a document about 'your performance' that arrived fully written top to bottom, with zero room to add your own version?",
  q092: "Is there a formal escalation process but when you escalate something the problem comes back to you unresolved with a note to 'handle it at team level'?",
  q093: "Did the formula for calculating your bonus change right after the period that bonus was supposed to reward had already closed?",
  q094: "Are there weekly recurring meetings that could clearly be an email but are mandatory because 'it's team culture'?",
  q095: "Was the hybrid work model designed according to managers' preferences without any real consultation with employees?",
  q096: "Did you ask HR something simple and get invited, five minutes later, to a meeting titled 'quick chat' that lasted 45 minutes?",
  q097: "Did a benefit you'd had since you joined disappear overnight, wrapped in the phrase 'policy update'?",
  q098: "Are your informal responsibilities so different from your official job description that you can't explain what you do using your contract title?",
  q099: "When a colleague leaves, is the only official word that the company 'wishes them success in their next challenge,' full stop?",
  q100: "After answering all these questions, do you still have your work chat open at 11pm because 'you're probably awake anyway'?",
};
