/** @readonly EITPL question pool — English (100 items) */
export const POOL_TEXTS_EN = {
  q001: "Does your company use mountain or mountaineering metaphors in HR presentations?",
  q002: "Were you demoted or had your salary cut in the last 12 months?",
  q003: "Were you promised a promotion that has been more than 6 months without materializing?",
  q004: "Are mistakes held against you in reviews only when they're yours, but not when your lead makes them?",
  q005: "Is the company in cost-cutting mode but managers still go to offsites with open bar?",
  q006: "Were you asked to organize a company event after layoffs were announced?",
  q007: "Is your current salary above the ceiling for your own level according to the new grading system?",
  q008: "The last time you asked about your promotion, were you told 'we've got your back' with no concrete date?",
  q009: "Does the evaluation system have more levels than before but it's harder to move up?",
  q010: "Have you been unable to reach even the first sub-level of your current category for more than 3 months?",
  q011: "Were you called to a 1:1 to be told you left early one day, while word is going around that 'everyone is disengaged' even though you don't lead the team or even the floor Slack channel?",
  q012: "Do you receive WhatsApp messages from your manager after 10pm followed by 'not urgent, reply when you can'?",
  q013: "Did your company announce mandatory return to office just when the most people were quitting?",
  q014: "Did the company hand out pizza to celebrate their best quarter ever while your raise request is still 'under review'?",
  q015: "Did your manager use the phrase 'we're a family here' with a completely straight face in the last 6 months?",
  q016: "Did the calibration meeting last four hours and you ended up with a lower rating than what you'd agreed with your lead?",
  q017: "Is there someone on your team who delivers less but has a better evaluation because they have 'good rapport' with the manager?",
  q018: "Are you on call or doing pager duty without it being reflected in any part of your compensation?",
  q019: "Was there a reorg that left you with exactly the same job but a different title that sounds like a demotion?",
  q020: "Did the company send an email about mental wellness or stress management at 11pm on a Tuesday?",
  q021: "Did your bonus arrive incomplete, late, or with an explanation that basically said 'trust us'?",
  q022: "Has your salary been frozen for over a year while inflation chipped away at your purchasing power in installments?",
  q023: "Did you present an initiative that was rejected, and months later your lead presented it as their own to the director?",
  q024: "Were you put on a formal improvement plan without having received any documented negative feedback beforehand?",
  q025: "Does your company use stack ranking, meaning someone on the team has to get a bad evaluation even though everyone met their goals?",
  q026: "Did the daily standup turn into a meeting where your manager asks about each of your tasks in front of everyone?",
  q027: "Are there Jira tickets that have been open for months because nobody knows who the real owner is?",
  q028: "Does the sprint retro always end with the same three action items that never get implemented before the next retro?",
  q029: "Did the project scope grow 40% after kickoff without anyone adjusting the deadline or headcount?",
  q030: "Did the company announce a 'new strategic chapter' or 'transformation journey' in the same communication where they announced layoffs?",
  q031: "Was team building on a Friday night at a place the manager chose, and attendance was recorded somewhere?",
  q032: "Do HR emails talk about 'psychological safety' but raising a real problem has real consequences?",
  q033: "Does the company have a wellness program with a meditation app, yoga classes, and weekly newsletter, but no salary adjustment?",
  q034: "Were your vacation days denied for 'business needs' in the same period your manager was able to take theirs?",
  q035: "Did you fill out an employee satisfaction survey and the results were used to justify a policy that was clearly already decided?",
  q036: "Does your annual review feedback include situations from a year ago that were never mentioned to you at the time?",
  q037: "Did two key people leave the team and you were told you'd cover their responsibilities 'temporarily' with no change in compensation?",
  q038: "Did the company cancel the collective bonus for a bad year but C-level equity packages saw no adjustment?",
  q039: "Does your company have an open-door policy but people who actually use it end up labeled 'difficult to work with'?",
  q040: "Were you given a promotion to a title that sounds better but salary and actual responsibilities are exactly the same?",
  q041: "Does nemawashi at your company consist of being so exhausted by prior consultations that by the time the formal decision arrives you don't object to anything?",
  q042: "Is attendance at nomikai or team dinners technically voluntary but those who don't go show up in reviews as 'not very committed'?",
  q043: "Did your company implement OKRs but your year-end evaluation has no verifiable connection to those objectives?",
  q044: "Are all-hands questions answered with pre-prepared slides and uncomfortable questions redirected to 'another channel'?",
  q045: "Has the roadmap changed so many times in the last quarter that you can no longer explain to an outsider exactly what you're working on?",
  q046: "Is there a colleague who joined after you, earns more than you, and was hired directly by the manager with no open process or standard interviews?",
  q047: "Did the role they told you was 'eliminated' reappear posted under a different name three months after you left?",
  q048: "Did a resigning colleague's offboarding include you permanently absorbing their responsibilities with no formal recognition?",
  q049: "Do new hires get paid in dollars while you've been paid in local currency for years with the same title?",
  q050: "Did accrued vacation days you could never take expire per internal policy with no financial compensation or extra days?",
  q051: "Can't your manager explain with concrete criteria what you need to achieve to move to the next level?",
  q052: "Is the People team that designed the new grading system not subject to the same grading system they designed?",
  q053: "Did the company announce 'record investment in people' in the same quarter they froze hiring and canceled training?",
  q054: "Did you get an 'exceeds expectations' rating but the raise didn't cover even half of that year's inflation?",
  q055: "Was your annual review conducted by someone who's known you for less than two months and never saw your work directly?",
  q056: "At your company, does being visible in the office matter more for promotion than concrete deliverables?",
  q057: "Are org chart changes that directly affect you announced Friday at 5pm by email?",
  q058: "Were you asked to complete a detailed self-assessment knowing the decision on your evaluation was already made before you submitted it?",
  q059: "Do your company's DEI initiatives have zero budget but a beautiful deck presented at every all-hands?",
  q060: "Does your company say it's agile but no real process changed in the last two years and waterfall is still the de facto standard?",
  q061: "Is system technical debt mentioned as a priority in every retro but never appears on the approved roadmap?",
  q062: "Do you systematically work more hours than your contract and it's not recorded in any system or evaluation?",
  q063: "When you asked for a raise, were you told 'the market' determines your compensation is fair without showing you any market data?",
  q064: "Is the official policy flexible remote work but your manager messages you if you're not active in chat before 9am?",
  q065: "Do training opportunities exist on the company portal but there's always a reason you can't access them this quarter?",
  q066: "Did your peers give you positive feedback in the 360 review but your manager lowered the final score 'to make it more balanced'?",
  q067: "Did the last reorg result in your manager now reporting to someone who has no idea what your area does?",
  q068: "Does mandatory return to office apply to your team but your main stakeholders keep working fully remote?",
  q069: "Has the hiring process for a position on your team taken more than six months but you're expected to deliver full-team results now?",
  q070: "Was someone external offered the position you were aspiring to internally without you being told there was an open process?",
  q071: "Did the email about company values and culture arrive the same day someone in your area was let go without explanation?",
  q072: "Were the overtime hours you worked during the last crunch never compensated with money or additional rest days?",
  q073: "Are you the informal onboarding reference for new hires without that affecting your official workload or evaluation?",
  q074: "Was the technical training budget cut but leadership retreat budget increased?",
  q075: "Is the task management system so complex you spend more time administrating work in the tool than doing the work itself?",
  q076: "Were you assigned as a mentor to a colleague with no formal recognition, no reduction in your workload, and no weight in your evaluation?",
  q077: "Do difficult conversations HR has with you happen without witnesses but conclusions are documented unilaterally?",
  q078: "Does your company have a no-rehire policy but after you left they informally called you for 'specific consultations' without pay?",
  q079: "Did you work flat out for months on a project that was canceled the week before launch with no formal retrospective or recognition?",
  q080: "Did your actual responsibilities change significantly in the last year without your job description or compensation being updated?",
  q081: "Does your company have a continuous feedback policy but in practice the only feedback you regularly receive is negative?",
  q082: "Did sprint planning become theater where the manager arrives with scope already decided and the ceremony exists to pretend the team participated?",
  q083: "Were you sold flexible hours but your mandatory recurring meetings cover slots from 8am to 7pm?",
  q084: "Was a colleague let go with an official explanation that doesn't match at all what everyone on the team knows really happened?",
  q085: "Does the company measure engagement with an annual survey whose results are never shared or produce verifiable changes?",
  q086: "Does your lead talk about ownership and autonomy at every all-hands but in practice vetoed every important decision you made on your own?",
  q087: "Was your project budget cut mid-execution without anyone adjusting scope or delivery date?",
  q088: "Did you find out about a change that directly affects you in a group meeting with no prior notice, alongside people who have nothing to do with it?",
  q089: "Did the company organize a hackathon or innovation day but none of the ideas generated were implemented or appear on any roadmap?",
  q090: "Does your manager talk about long-term career plans at the company when they've been in the role for less than a year?",
  q091: "Were you asked to sign a performance improvement document drafted exclusively by HR without being able to add anything?",
  q092: "Is there a formal escalation process but when you escalate something the problem comes back to you unresolved with a note to 'handle it at team level'?",
  q093: "Was the formula for calculating your variable compensation modified after the evaluation period it applies to ended?",
  q094: "Are there weekly recurring meetings that could clearly be an email but are mandatory because 'it's team culture'?",
  q095: "Was the hybrid work model designed according to managers' preferences without any real consultation with employees?",
  q096: "Did you receive formal HR communication the same day you asked for information about your rights or employment conditions?",
  q097: "Did the company reduce leave or benefits that existed when you joined and communicated it as a 'policy update' with no room for discussion?",
  q098: "Are your informal responsibilities so different from your official job description that you can't explain what you do using your contract title?",
  q099: "Was a colleague's exit so opaque that a week later nobody knows for sure if they quit or were fired?",
  q100: "After answering all these questions, do you still have your work chat open at 11pm because 'you're probably awake anyway'?",
};
