/** @readonly EITPL question pool — Spanish (100 items) */
export const POOL_TEXTS_ES = {
  q001: "¿Tu empresa usa metáforas de montaña o alpinismo en las presentaciones de RRHH?",
  q002: "¿Tu empresa le puso un nombre elegante tipo 'reestructuración de bandas' a lo que en criollo fue una bajada de sueldo?",
  q003: "¿Te prometieron un ascenso que lleva más de 6 meses sin materializarse?",
  q004: "¿Los errores te los cobran en la evaluación solo cuando son tuyos, pero no cuando los comete el lead?",
  q005: "¿La empresa está en modo ahorro pero los managers siguen yendo a offsite con open bar?",
  q006: "¿Te pidieron organizar un evento de empresa después de anunciar recortes?",
  q007: "¿Te explicaron el nuevo sistema de grading con un gráfico tan complicado que ni RRHH podía decirte en qué banda estabas vos?",
  q008: "¿La última vez que preguntaste por tu ascenso te respondieron con 'te apoyamos' sin fecha concreta?",
  q009: "¿El sistema de evaluación ahora tiene más niveles, más siglas y más reuniones, pero de alguna manera subir un escalón es más difícil que antes?",
  q010: "¿Llevás meses 'a punto de subir de nivel' y esa frase ya es un chiste interno en tu equipo?",
  q011: "¿Te citaron a un 1:1 para decirte que te fuiste temprano un día, y encima anda circulando que 'todos están desmotivados' sin que vos lideres ni el grupo de WhatsApp del piso?",
  q012: "¿Recibís mensajes de WhatsApp de tu manager después de las 22hs seguidos de 'no es urgente, contestá cuando puedas'?",
  q013: "¿Tu empresa anunció la vuelta obligatoria a la oficina justo cuando más personas estaban renunciando?",
  q014: "¿La empresa repartió pizzas para celebrar el mejor trimestre de su historia y tu pedido de aumento sigue 'en evaluación'?",
  q015: "¿Tu manager usó la frase 'acá somos una familia' con cara completamente seria en los últimos 6 meses?",
  q016: "¿La reunión de calibración duró cuatro horas y terminaste con una nota más baja que la que habías acordado con tu lead?",
  q017: "¿Hay alguien en tu equipo que entrega menos pero tiene mejor evaluación porque tiene 'buena llegada' con el manager?",
  q018: "¿Hacés guardia o estás on-call sin que eso aparezca reflejado en ningún rubro de tu compensación?",
  q019: "¿Hubo una reorganización que te dejó con exactamente el mismo trabajo pero con un título diferente que suena a degradación?",
  q020: "¿La empresa mandó un mail sobre bienestar mental o gestión del estrés a las 23hs de un martes?",
  q021: "¿Tu aguinaldo llegó incompleto, tarde, o con una explicación que básicamente decía 'confiá en nosotros'?",
  q022: "¿Tu sueldo lleva más de un año congelado mientras la inflación te comió el poder adquisitivo en cuotas?",
  q023: "¿Presentaste una iniciativa que fue rechazada y meses después tu lead la presentó como propia ante el director?",
  q024: "¿Te llamaron a una charla 'informal' que terminó siendo un plan de mejora formal, y la única alerta previa fue una mirada rara de tu manager en el pasillo?",
  q025: "¿Tu empresa tiene una curva de evaluación tan forzada que, aunque todo el equipo haya cumplido sus objetivos, igual alguien tiene que salir 'necesita mejorar'?",
  q026: "¿El standup diario se convirtió en una reunión donde tu manager te pregunta por cada tarea frente a todos los demás?",
  q027: "¿Hay tickets de Jira que llevan meses abiertos porque nadie sabe quién es el owner real?",
  q028: "¿La retro del sprint termina siempre con los mismos tres action items que nunca se implementan antes de la próxima retro?",
  q029: "¿El scope del proyecto creció un 40% después del kick-off sin que nadie ajustara el deadline ni el headcount?",
  q030: "¿La empresa anunció un 'nuevo capítulo estratégico' o 'transformation journey' en el mismo comunicado donde informó los despidos?",
  q031: "¿El team building fue un viernes a la noche en un lugar que eligió el manager y la asistencia quedó anotada en algún lado?",
  q032: "¿Los mails de RRHH hablan de 'psychological safety' pero señalar un problema real tiene consecuencias reales?",
  q033: "¿La empresa tiene programa de bienestar con app de meditación, clases de yoga y newsletter semanal, pero sin ajuste salarial?",
  q034: "¿Te denegaron las vacaciones por 'necesidades del negocio' en el mismo período en que tu manager sí pudo tomárselas?",
  q035: "¿Llenaste una encuesta de clima laboral y los resultados se usaron para justificar una política que claramente ya estaba decidida?",
  q036: "¿El feedback de tu evaluación anual incluye situaciones de hace un año que nunca te mencionaron en su momento?",
  q037: "¿Se fueron dos personas clave del equipo y te dijeron que cubrirías sus responsabilidades 'temporalmente' sin cambio en tu compensación?",
  q038: "¿Cancelaron el bono de todo el equipo por 'mal año' pero el offsite de liderazgo del trimestre siguiente fue en un lugar con pileta?",
  q039: "¿Tu empresa tiene política de puertas abiertas pero quienes la usan de verdad terminan etiquetados como 'difíciles de trabajar'?",
  q040: "¿Te dieron una promotion a un título que suena mejor pero el sueldo y las responsabilidades reales son exactamente los mismos?",
  q041: "¿El proceso de nemawashi en tu empresa consiste en que cuando llega la decisión formal ya estás tan agotado de las consultas previas que no objetás nada?",
  q042: "¿La asistencia al nomikai o cenas de equipo es técnicamente voluntaria pero los que no van aparecen en las evaluaciones como 'poco comprometidos'?",
  q043: "¿Tu empresa implementó OKRs pero tu evaluación de fin de año no tiene ninguna relación verificable con esos objetivos?",
  q044: "¿Las preguntas en el all-hands se responden con slides preparados de antemano y las preguntas incómodas se derivan a 'otro canal'?",
  q045: "¿El roadmap cambió tantas veces en el último trimestre que ya no podés explicarle a alguien de afuera en qué estás trabajando exactamente?",
  q046: "¿Hay alguien en tu equipo que entró después que vos, gana más, y nadie te puede explicar bien por qué?",
  q047: "¿Un puesto que 'eliminaron por reestructuración' volvió a aparecer publicado tres meses después con un nombre distinto?",
  q048: "¿Heredaste las tareas de un compañero que se fue hace meses y el 'es temporal, ya conseguimos reemplazo' todavía no se cumplió?",
  q049: "¿Los contratados nuevos cobran en dólares mientras vos cobrás en pesos desde hace años con el mismo cargo?",
  q050: "¿Tenés un cajón de días de vacaciones acumulados que nunca pudiste usar y que, misteriosamente, cada vez son menos según el sistema de RRHH?",
  q051: "¿Tu manager no sabe explicar con criterios concretos qué necesitás lograr para subir al siguiente nivel?",
  q052: "¿El equipo de People que diseñó el nuevo sistema de grading no está sujeto al mismo sistema de grading que diseñó?",
  q053: "¿La empresa anunció 'inversión récord en las personas' en el mismo trimestre que congelaron las contrataciones y cancelaron las capacitaciones?",
  q054: "¿Tuviste calificación de 'supera expectativas' en la evaluación pero el aumento que te dieron no cubre ni la mitad de la inflación del año?",
  q055: "¿Tu evaluación anual la hizo alguien que te conoce hace menos tiempo del que tarda un café en enfriarse?",
  q056: "¿En tu empresa estar visible en la oficina importa más para el ascenso que los entregables concretos?",
  q057: "¿Los cambios de organigrama que te afectan directamente se anuncian los viernes a las 17hs por mail?",
  q058: "¿Te pidieron completar un self-assessment detallado sabiendo que la decisión sobre tu evaluación ya estaba tomada antes de que lo enviaras?",
  q059: "¿Tu empresa tiene una iniciativa de 'innovación' con logo propio, deck hermoso y stickers, pero presupuesto real de exactamente cero?",
  q060: "¿Tu empresa dice que es ágil pero ningún proceso real cambió en los últimos dos años y el waterfall sigue siendo el estándar de facto?",
  q061: "¿La deuda técnica del sistema se menciona en cada retro como prioridad pero nunca aparece en el roadmap aprobado?",
  q062: "¿Tu jornada 'de 9 a 18' es en realidad de 9 a 'cuando termine', y esa diferencia nunca aparece en tu recibo de sueldo?",
  q063: "¿Cuando pediste un aumento te dijeron que 'el mercado' determina que tu compensación es justa sin mostrarte ningún dato de mercado?",
  q064: "¿La política oficial es de trabajo remoto flexible pero tu manager te escribe si no estás activo en el chat antes de las 9am?",
  q065: "¿Las oportunidades de capacitación existen en el portal de la empresa pero siempre hay una razón por la cual no podés acceder a ellas este trimestre?",
  q066: "¿Tus pares te dieron feedback positivo en la evaluación 360 pero tu manager bajó la nota final 'para que sea más balanceada'?",
  q067: "¿El último reorg resultó en que tu manager ahora reporta a alguien que no tiene idea de lo que hace tu área?",
  q068: "¿La vuelta a la oficina obligatoria aplica a tu equipo pero tus stakeholders principales siguen trabajando completamente en remoto?",
  q069: "¿El proceso de contratación para cubrir una posición en tu equipo lleva más de seis meses pero te piden resultados de equipo completo para ahora?",
  q070: "¿Le ofrecieron el puesto que vos querías a alguien de afuera, y te enteraste por LinkedIn antes que por tu propia empresa?",
  q071: "¿El mail sobre los 'valores de la empresa' siempre parece llegar justo la semana que hay rumores de recorte de personal?",
  q072: "¿Sobreviviste a un crunch de varias semanas y la única compensación fue un mail de 'gracias equipo' con un emoji de fuego?",
  q073: "¿Sos el referente informal de onboarding de los nuevos sin que eso tenga ningún impacto en tu carga de trabajo oficial ni en tu evaluación?",
  q074: "¿Recortaron el presupuesto de capacitación técnica pero aumentaron el presupuesto de los retiros de liderazgo?",
  q075: "¿El sistema de gestión de tareas es tan complejo que pasás más tiempo administrando el trabajo en la herramienta que haciéndolo en sí?",
  q076: "¿Te asignaron como mentor de un compañero sin reconocimiento formal, sin reducción de tu carga y sin peso en tu evaluación?",
  q077: "¿Tuviste una charla incómoda con RRHH que después se resumió en un mail con una versión de los hechos que vos no terminás de reconocer?",
  q078: "¿Tu empresa tiene política de no-recontratación pero después de irte te llamaron informalmente para 'consultas puntuales' sin remuneración?",
  q079: "¿Laburaste a full durante meses en un proyecto que fue cancelado la semana antes del lanzamiento sin retrospectiva formal ni reconocimiento?",
  q080: "¿Tus responsabilidades reales cambiaron significativamente en el último año sin que se actualizara tu job description ni tu compensación?",
  q081: "¿Tu empresa tiene política de feedback continuo pero en la práctica el único feedback que recibís regularmente es el negativo?",
  q082: "¿El sprint planning se convirtió en teatro donde el manager ya viene con el scope decidido y la ceremonia existe para aparentar que el equipo participó?",
  q083: "¿Te vendieron horario flexible pero tus reuniones recurrentes obligatorias cubren franjas de las 8am a las 7pm?",
  q084: "¿Cuando alguien se va de la empresa, la versión oficial nunca coincide con lo que todo el equipo ya sabía por el chat paralelo?",
  q085: "¿La empresa mide el engagement con una encuesta anual cuyos resultados nunca se comparten ni generan cambios verificables?",
  q086: "¿Tu lead habla de ownership y autonomía en todos los all-hands pero en la práctica vetó todas las decisiones importantes que tomaste por tu cuenta?",
  q087: "¿El presupuesto de tu proyecto fue recortado a mitad de ejecución sin que nadie ajustara el alcance ni la fecha de entrega?",
  q088: "¿Te enteraste de un cambio que te afecta directamente en una reunión grupal sin previo aviso, junto con gente que no tiene nada que ver?",
  q089: "¿La empresa organizó un hackathon o innovation day pero ninguna de las ideas generadas se implementó ni aparece en ningún roadmap?",
  q090: "¿Tu manager te habla del plan de carrera a largo plazo en la empresa cuando él mismo lleva menos de un año en el puesto?",
  q091: "¿Te pidieron firmar un documento sobre 'tu desempeño' que ya venía redactado de punta a punta, sin ningún espacio para que agregues tu versión?",
  q092: "¿Existe un proceso formal de escalamiento pero cuando escalás algo el problema vuelve a vos sin resolución y con una nota de 'gestionalo a nivel de equipo'?",
  q093: "¿La fórmula para calcular tu bono cambió justo después de cerrado el período que ese bono debía premiar?",
  q094: "¿Hay reuniones semanales recurrentes que claramente podrían ser un mail pero son obligatorias porque 'es cultura del equipo'?",
  q095: "¿El modelo de trabajo híbrido fue diseñado según las preferencias de los managers sin ninguna consulta real a los empleados?",
  q096: "¿Preguntaste algo simple en RRHH y a los cinco minutos te invitaron a una reunión con el asunto 'charla rápida' que duró 45 minutos?",
  q097: "¿Un beneficio que tenías desde que entraste desapareció de un día para el otro, envuelto en la frase 'actualización de política'?",
  q098: "¿Tus responsabilidades informales son tan distintas de tu job description oficial que no podés explicar lo que hacés usando el título de tu contrato?",
  q099: "¿Cuando un compañero se va, la única comunicación oficial es que 'le desean éxitos en sus próximos desafíos', y ni una palabra más?",
  q100: "¿Después de responder todas estas preguntas, todavía tenés el chat del trabajo prendido a las 11 de la noche porque 'igual ya estás despierto'?",
};
